# Generated by Django 5.2.3 on 2025-07-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='boolean_field',
            field=models.BooleanField(default=False),
        ),
    ]
