# Generated by Django 5.2.3 on 2025-07-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_boolean_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='boolean_field',
            new_name='task_complete',
        ),
    ]
